import type { Metadata } from "next";
import localFont from "next/font/local";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Navbar } from "./navabr";
import { AuthProvider } from "./auth/auth-context";
import { StoreProvider } from "./lib/data-store/store";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: "400",
  subsets: ["latin"],
  fallback: ["sans-serif"],
  style: "normal",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased px-12 grid grid-cols-1 gap-12 `} >
        <AuthProvider>
          <StoreProvider>
            <Navbar />
            <Toaster />
            {props.children}
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
